// <auto-generated />
using System;
using MCRSearch.src.MCRSearch.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MCRSearch.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240216222949_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MCRSearch.src.MCRSearch.Core.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "02174cf0–9412–4cfe-afbf-59f706d72cf6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cc4d29b6-94ed-4b3e-b244-489b0195c17b",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "admin",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAENCGropD1B8L4/Wp+2vGkZEkhTqtDGZJ1SP1GMoZ62bwaDFx33Kh3WNx7BzgIEVSWg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "578308c7-ca68-415b-a4c9-1e42a46f3830",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("MCRSearch.src.MCRSearch.Core.Entities.AvailableVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PickUpCityId")
                        .HasColumnType("int");

                    b.Property<int>("ReturnCityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PickUpCityId");

                    b.HasIndex("ReturnCityId");

                    b.HasIndex("VehicleId");

                    b.ToTable("AvailableVehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3469),
                            PickUpCityId = 1,
                            ReturnCityId = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3476),
                            PickUpCityId = 1,
                            ReturnCityId = 1,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3477),
                            PickUpCityId = 1,
                            ReturnCityId = 1,
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3478),
                            PickUpCityId = 1,
                            ReturnCityId = 1,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3479),
                            PickUpCityId = 1,
                            ReturnCityId = 1,
                            VehicleId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3480),
                            PickUpCityId = 1,
                            ReturnCityId = 2,
                            VehicleId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3481),
                            PickUpCityId = 1,
                            ReturnCityId = 2,
                            VehicleId = 5
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3482),
                            PickUpCityId = 2,
                            ReturnCityId = 1,
                            VehicleId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3482),
                            PickUpCityId = 3,
                            ReturnCityId = 3,
                            VehicleId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3483),
                            PickUpCityId = 3,
                            ReturnCityId = 3,
                            VehicleId = 10
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3484),
                            PickUpCityId = 3,
                            ReturnCityId = 3,
                            VehicleId = 14
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3485),
                            PickUpCityId = 3,
                            ReturnCityId = 3,
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3486),
                            PickUpCityId = 4,
                            ReturnCityId = 3,
                            VehicleId = 12
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3487),
                            PickUpCityId = 4,
                            ReturnCityId = 3,
                            VehicleId = 14
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3488),
                            PickUpCityId = 4,
                            ReturnCityId = 3,
                            VehicleId = 20
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3488),
                            PickUpCityId = 4,
                            ReturnCityId = 3,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3517),
                            PickUpCityId = 2,
                            ReturnCityId = 2,
                            VehicleId = 17
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3518),
                            PickUpCityId = 2,
                            ReturnCityId = 2,
                            VehicleId = 14
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3519),
                            PickUpCityId = 2,
                            ReturnCityId = 2,
                            VehicleId = 19
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3520),
                            PickUpCityId = 4,
                            ReturnCityId = 4,
                            VehicleId = 20
                        });
                });

            modelBuilder.Entity("MCRSearch.src.MCRSearch.Core.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3232),
                            DepartmentId = 1,
                            Name = "Bogotá D.C."
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3236),
                            DepartmentId = 1,
                            Name = "Tunja"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3237),
                            DepartmentId = 2,
                            Name = "Brasilia"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3238),
                            DepartmentId = 2,
                            Name = "Goiânia"
                        });
                });

            modelBuilder.Entity("MCRSearch.src.MCRSearch.Core.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3169),
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3189),
                            Name = "Brazil"
                        });
                });

            modelBuilder.Entity("MCRSearch.src.MCRSearch.Core.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3210),
                            Name = "Cundinamarca"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 2,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3213),
                            Name = "Goiás"
                        });
                });

            modelBuilder.Entity("MCRSearch.src.MCRSearch.Core.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VehicleBrandId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleBrandId");

                    b.HasIndex("VehicleModelId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3430),
                            VehicleBrandId = 1,
                            VehicleModelId = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3433),
                            VehicleBrandId = 2,
                            VehicleModelId = 2,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3434),
                            VehicleBrandId = 3,
                            VehicleModelId = 3,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3435),
                            VehicleBrandId = 4,
                            VehicleModelId = 4,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3435),
                            VehicleBrandId = 5,
                            VehicleModelId = 5,
                            VehicleTypeId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3436),
                            VehicleBrandId = 6,
                            VehicleModelId = 6,
                            VehicleTypeId = 4
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3437),
                            VehicleBrandId = 7,
                            VehicleModelId = 7,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3438),
                            VehicleBrandId = 8,
                            VehicleModelId = 8,
                            VehicleTypeId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3439),
                            VehicleBrandId = 9,
                            VehicleModelId = 9,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3440),
                            VehicleBrandId = 10,
                            VehicleModelId = 10,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3442),
                            VehicleBrandId = 11,
                            VehicleModelId = 11,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3443),
                            VehicleBrandId = 12,
                            VehicleModelId = 12,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3444),
                            VehicleBrandId = 13,
                            VehicleModelId = 13,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3444),
                            VehicleBrandId = 14,
                            VehicleModelId = 14,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3445),
                            VehicleBrandId = 15,
                            VehicleModelId = 15,
                            VehicleTypeId = 3
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3446),
                            VehicleBrandId = 16,
                            VehicleModelId = 16,
                            VehicleTypeId = 3
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3447),
                            VehicleBrandId = 17,
                            VehicleModelId = 17,
                            VehicleTypeId = 3
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3448),
                            VehicleBrandId = 18,
                            VehicleModelId = 18,
                            VehicleTypeId = 3
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3449),
                            VehicleBrandId = 19,
                            VehicleModelId = 19,
                            VehicleTypeId = 3
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3449),
                            VehicleBrandId = 20,
                            VehicleModelId = 20,
                            VehicleTypeId = 1
                        });
                });

            modelBuilder.Entity("MCRSearch.src.MCRSearch.Core.Entities.VehicleBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("VehicleBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3256),
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3257),
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3258),
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3260),
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3260),
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3261),
                            Name = "Jeep"
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3262),
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3263),
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3263),
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3264),
                            Name = "Subaru"
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3265),
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3265),
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3267),
                            Name = "GMC"
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3267),
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3332),
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3333),
                            Name = "Lexus"
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3334),
                            Name = "Kia"
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3335),
                            Name = "Jaguar"
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3336),
                            Name = "Land Rover"
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3336),
                            Name = "Ford"
                        });
                });

            modelBuilder.Entity("MCRSearch.src.MCRSearch.Core.Entities.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3373),
                            Name = "Camry"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3374),
                            Name = "Accord"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3375),
                            Name = "Explorer"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3376),
                            Name = "Malibu"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3377),
                            Name = "Rogue"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3378),
                            Name = "Wrangler"
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3379),
                            Name = "Golf"
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3380),
                            Name = "X5"
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3380),
                            Name = "C-Class"
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3381),
                            Name = "Outback"
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3382),
                            Name = "F-150"
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3382),
                            Name = "Model S"
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3383),
                            Name = "Sierra"
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3384),
                            Name = "Q7"
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3384),
                            Name = "Santa Fe"
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3385),
                            Name = "RX"
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3386),
                            Name = "Sportage"
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3386),
                            Name = "F-PACE"
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3387),
                            Name = "Discovery"
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3387),
                            Name = "Mustang"
                        });
                });

            modelBuilder.Entity("MCRSearch.src.MCRSearch.Core.Entities.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3411),
                            Name = "Automóvil"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3413),
                            Name = "Camioneta"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3413),
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 2, 16, 17, 29, 49, 159, DateTimeKind.Local).AddTicks(3414),
                            Name = "Campero"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "341743f0-asd2-42de-afbf-59kmkkmk72cf6",
                            ConcurrencyStamp = "341743f0-asd2-42de-afbf-59kmkkmk72cf6",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "02174cf0–9412–4cfe-afbf-59f706d72cf6",
                            RoleId = "341743f0-asd2-42de-afbf-59kmkkmk72cf6"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MCRSearch.src.MCRSearch.Core.Entities.AvailableVehicle", b =>
                {
                    b.HasOne("MCRSearch.src.MCRSearch.Core.Entities.City", "PickUpCity")
                        .WithMany()
                        .HasForeignKey("PickUpCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCRSearch.src.MCRSearch.Core.Entities.City", "ReturnCity")
                        .WithMany()
                        .HasForeignKey("ReturnCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCRSearch.src.MCRSearch.Core.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PickUpCity");

                    b.Navigation("ReturnCity");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("MCRSearch.src.MCRSearch.Core.Entities.City", b =>
                {
                    b.HasOne("MCRSearch.src.MCRSearch.Core.Entities.Department", "Department")
                        .WithMany("Cities")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MCRSearch.src.MCRSearch.Core.Entities.Department", b =>
                {
                    b.HasOne("MCRSearch.src.MCRSearch.Core.Entities.Country", "Country")
                        .WithMany("Departments")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MCRSearch.src.MCRSearch.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("MCRSearch.src.MCRSearch.Core.Entities.VehicleBrand", "VehicleBrand")
                        .WithMany()
                        .HasForeignKey("VehicleBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCRSearch.src.MCRSearch.Core.Entities.VehicleModel", "VehicleModel")
                        .WithMany()
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCRSearch.src.MCRSearch.Core.Entities.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleBrand");

                    b.Navigation("VehicleModel");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MCRSearch.src.MCRSearch.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MCRSearch.src.MCRSearch.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCRSearch.src.MCRSearch.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MCRSearch.src.MCRSearch.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MCRSearch.src.MCRSearch.Core.Entities.Country", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("MCRSearch.src.MCRSearch.Core.Entities.Department", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
